export default {
    DISPLAYTE: 'display_te',
    SETCONN: 'set_conn',
    // SERVERDATA: 'server_data',
    PLAYERINFO: 'player_info',
    PLAYERROLE: 'player_role',
    CON_ON: 'connection_on',
    LOGININPUT: 'login_input',
    GAMEINFO: 'game_info',
    CREATEBUTTONWASCLICKED: 'create_button_was_clicked',
    JOINBUTTONWASCLICKED: 'join_button_was_clicked',
    MODALACTIONS: 'modal_actions',
    PLAYEREVENT: 'player_event',
    USER_AUTH: 'user_auth',
    SIGNUPCLICKED: 'sign_up_was_clicked',
    PLAYERARRAYS: 'player_arrays',
    GAMEARRAYS: 'game_arrays',
}